name: selenide-en-us

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 4 * * *'

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Lint and Test with Gradle
      run: ./gradlew --no-daemon clean check
